name: Fly Deploy
on:
  push:
    branches:
      - main
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Wait for tests to succeed
          uses: lewagon/wait-on-check-action@v1.0.0
          with:
            ref: ${{ github.ref }}
            check-name: 'Run tests'
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            wait-interval: 20
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
